import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';
import { geistMono, geistSans, quickSand } from './font';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${quickSand.variable} ${geistSans.variable} ${geistMono.variable} ${quickSand.className} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
